# Generated by Django 3.1.6 on 2021-02-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone_number',
        ),
    ]
